apiVersion: v1
kind: Service
metadata:
  name: github-update-go-watcher
  namespace: '{{ "NAMESPACE" | env }}'
spec:
  ports:
  - name: http
    port: 9090
  selector:
    app: github-update-go-watcher
