// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/github-update-go-watcher/pkg"
	"github.com/bborbe/maintainer/maintainerconfig"
)

type GitHubClient struct {
	GetGoModStub        func(context.Context, pkg.Repo) ([]byte, error)
	getGoModMutex       sync.RWMutex
	getGoModArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.Repo
	}
	getGoModReturns struct {
		result1 []byte
		result2 error
	}
	getGoModReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	GetHeadSHAStub        func(context.Context, pkg.Repo) (string, error)
	getHeadSHAMutex       sync.RWMutex
	getHeadSHAArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.Repo
	}
	getHeadSHAReturns struct {
		result1 string
		result2 error
	}
	getHeadSHAReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	GetMaintainerConfigStub        func(context.Context, pkg.Repo) (maintainerconfig.MaintainerConfig, error)
	getMaintainerConfigMutex       sync.RWMutex
	getMaintainerConfigArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.Repo
	}
	getMaintainerConfigReturns struct {
		result1 maintainerconfig.MaintainerConfig
		result2 error
	}
	getMaintainerConfigReturnsOnCall map[int]struct {
		result1 maintainerconfig.MaintainerConfig
		result2 error
	}
	ListReposStub        func(context.Context, string) ([]pkg.Repo, error)
	listReposMutex       sync.RWMutex
	listReposArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	listReposReturns struct {
		result1 []pkg.Repo
		result2 error
	}
	listReposReturnsOnCall map[int]struct {
		result1 []pkg.Repo
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *GitHubClient) GetGoMod(arg1 context.Context, arg2 pkg.Repo) ([]byte, error) {
	fake.getGoModMutex.Lock()
	ret, specificReturn := fake.getGoModReturnsOnCall[len(fake.getGoModArgsForCall)]
	fake.getGoModArgsForCall = append(fake.getGoModArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.Repo
	}{arg1, arg2})
	stub := fake.GetGoModStub
	fakeReturns := fake.getGoModReturns
	fake.recordInvocation("GetGoMod", []interface{}{arg1, arg2})
	fake.getGoModMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) GetGoModCallCount() int {
	fake.getGoModMutex.RLock()
	defer fake.getGoModMutex.RUnlock()
	return len(fake.getGoModArgsForCall)
}

func (fake *GitHubClient) GetGoModCalls(stub func(context.Context, pkg.Repo) ([]byte, error)) {
	fake.getGoModMutex.Lock()
	defer fake.getGoModMutex.Unlock()
	fake.GetGoModStub = stub
}

func (fake *GitHubClient) GetGoModArgsForCall(i int) (context.Context, pkg.Repo) {
	fake.getGoModMutex.RLock()
	defer fake.getGoModMutex.RUnlock()
	argsForCall := fake.getGoModArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *GitHubClient) GetGoModReturns(result1 []byte, result2 error) {
	fake.getGoModMutex.Lock()
	defer fake.getGoModMutex.Unlock()
	fake.GetGoModStub = nil
	fake.getGoModReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetGoModReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.getGoModMutex.Lock()
	defer fake.getGoModMutex.Unlock()
	fake.GetGoModStub = nil
	if fake.getGoModReturnsOnCall == nil {
		fake.getGoModReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.getGoModReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetHeadSHA(arg1 context.Context, arg2 pkg.Repo) (string, error) {
	fake.getHeadSHAMutex.Lock()
	ret, specificReturn := fake.getHeadSHAReturnsOnCall[len(fake.getHeadSHAArgsForCall)]
	fake.getHeadSHAArgsForCall = append(fake.getHeadSHAArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.Repo
	}{arg1, arg2})
	stub := fake.GetHeadSHAStub
	fakeReturns := fake.getHeadSHAReturns
	fake.recordInvocation("GetHeadSHA", []interface{}{arg1, arg2})
	fake.getHeadSHAMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) GetHeadSHACallCount() int {
	fake.getHeadSHAMutex.RLock()
	defer fake.getHeadSHAMutex.RUnlock()
	return len(fake.getHeadSHAArgsForCall)
}

func (fake *GitHubClient) GetHeadSHACalls(stub func(context.Context, pkg.Repo) (string, error)) {
	fake.getHeadSHAMutex.Lock()
	defer fake.getHeadSHAMutex.Unlock()
	fake.GetHeadSHAStub = stub
}

func (fake *GitHubClient) GetHeadSHAArgsForCall(i int) (context.Context, pkg.Repo) {
	fake.getHeadSHAMutex.RLock()
	defer fake.getHeadSHAMutex.RUnlock()
	argsForCall := fake.getHeadSHAArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *GitHubClient) GetHeadSHAReturns(result1 string, result2 error) {
	fake.getHeadSHAMutex.Lock()
	defer fake.getHeadSHAMutex.Unlock()
	fake.GetHeadSHAStub = nil
	fake.getHeadSHAReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetHeadSHAReturnsOnCall(i int, result1 string, result2 error) {
	fake.getHeadSHAMutex.Lock()
	defer fake.getHeadSHAMutex.Unlock()
	fake.GetHeadSHAStub = nil
	if fake.getHeadSHAReturnsOnCall == nil {
		fake.getHeadSHAReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getHeadSHAReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetMaintainerConfig(arg1 context.Context, arg2 pkg.Repo) (maintainerconfig.MaintainerConfig, error) {
	fake.getMaintainerConfigMutex.Lock()
	ret, specificReturn := fake.getMaintainerConfigReturnsOnCall[len(fake.getMaintainerConfigArgsForCall)]
	fake.getMaintainerConfigArgsForCall = append(fake.getMaintainerConfigArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.Repo
	}{arg1, arg2})
	stub := fake.GetMaintainerConfigStub
	fakeReturns := fake.getMaintainerConfigReturns
	fake.recordInvocation("GetMaintainerConfig", []interface{}{arg1, arg2})
	fake.getMaintainerConfigMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) GetMaintainerConfigCallCount() int {
	fake.getMaintainerConfigMutex.RLock()
	defer fake.getMaintainerConfigMutex.RUnlock()
	return len(fake.getMaintainerConfigArgsForCall)
}

func (fake *GitHubClient) GetMaintainerConfigCalls(stub func(context.Context, pkg.Repo) (maintainerconfig.MaintainerConfig, error)) {
	fake.getMaintainerConfigMutex.Lock()
	defer fake.getMaintainerConfigMutex.Unlock()
	fake.GetMaintainerConfigStub = stub
}

func (fake *GitHubClient) GetMaintainerConfigArgsForCall(i int) (context.Context, pkg.Repo) {
	fake.getMaintainerConfigMutex.RLock()
	defer fake.getMaintainerConfigMutex.RUnlock()
	argsForCall := fake.getMaintainerConfigArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *GitHubClient) GetMaintainerConfigReturns(result1 maintainerconfig.MaintainerConfig, result2 error) {
	fake.getMaintainerConfigMutex.Lock()
	defer fake.getMaintainerConfigMutex.Unlock()
	fake.GetMaintainerConfigStub = nil
	fake.getMaintainerConfigReturns = struct {
		result1 maintainerconfig.MaintainerConfig
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) GetMaintainerConfigReturnsOnCall(i int, result1 maintainerconfig.MaintainerConfig, result2 error) {
	fake.getMaintainerConfigMutex.Lock()
	defer fake.getMaintainerConfigMutex.Unlock()
	fake.GetMaintainerConfigStub = nil
	if fake.getMaintainerConfigReturnsOnCall == nil {
		fake.getMaintainerConfigReturnsOnCall = make(map[int]struct {
			result1 maintainerconfig.MaintainerConfig
			result2 error
		})
	}
	fake.getMaintainerConfigReturnsOnCall[i] = struct {
		result1 maintainerconfig.MaintainerConfig
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) ListRepos(arg1 context.Context, arg2 string) ([]pkg.Repo, error) {
	fake.listReposMutex.Lock()
	ret, specificReturn := fake.listReposReturnsOnCall[len(fake.listReposArgsForCall)]
	fake.listReposArgsForCall = append(fake.listReposArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.ListReposStub
	fakeReturns := fake.listReposReturns
	fake.recordInvocation("ListRepos", []interface{}{arg1, arg2})
	fake.listReposMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *GitHubClient) ListReposCallCount() int {
	fake.listReposMutex.RLock()
	defer fake.listReposMutex.RUnlock()
	return len(fake.listReposArgsForCall)
}

func (fake *GitHubClient) ListReposCalls(stub func(context.Context, string) ([]pkg.Repo, error)) {
	fake.listReposMutex.Lock()
	defer fake.listReposMutex.Unlock()
	fake.ListReposStub = stub
}

func (fake *GitHubClient) ListReposArgsForCall(i int) (context.Context, string) {
	fake.listReposMutex.RLock()
	defer fake.listReposMutex.RUnlock()
	argsForCall := fake.listReposArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *GitHubClient) ListReposReturns(result1 []pkg.Repo, result2 error) {
	fake.listReposMutex.Lock()
	defer fake.listReposMutex.Unlock()
	fake.ListReposStub = nil
	fake.listReposReturns = struct {
		result1 []pkg.Repo
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) ListReposReturnsOnCall(i int, result1 []pkg.Repo, result2 error) {
	fake.listReposMutex.Lock()
	defer fake.listReposMutex.Unlock()
	fake.ListReposStub = nil
	if fake.listReposReturnsOnCall == nil {
		fake.listReposReturnsOnCall = make(map[int]struct {
			result1 []pkg.Repo
			result2 error
		})
	}
	fake.listReposReturnsOnCall[i] = struct {
		result1 []pkg.Repo
		result2 error
	}{result1, result2}
}

func (fake *GitHubClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *GitHubClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.GitHubClient = new(GitHubClient)
