// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/github-update-go-watcher/pkg"
)

type TaskPublisher struct {
	PublishCreateStub        func(context.Context, pkg.Candidate) bool
	publishCreateMutex       sync.RWMutex
	publishCreateArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.Candidate
	}
	publishCreateReturns struct {
		result1 bool
	}
	publishCreateReturnsOnCall map[int]struct {
		result1 bool
	}
	PublishDecisionStub        func(context.Context, pkg.Candidate) bool
	publishDecisionMutex       sync.RWMutex
	publishDecisionArgsForCall []struct {
		arg1 context.Context
		arg2 pkg.Candidate
	}
	publishDecisionReturns struct {
		result1 bool
	}
	publishDecisionReturnsOnCall map[int]struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *TaskPublisher) PublishCreate(arg1 context.Context, arg2 pkg.Candidate) bool {
	fake.publishCreateMutex.Lock()
	ret, specificReturn := fake.publishCreateReturnsOnCall[len(fake.publishCreateArgsForCall)]
	fake.publishCreateArgsForCall = append(fake.publishCreateArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.Candidate
	}{arg1, arg2})
	stub := fake.PublishCreateStub
	fakeReturns := fake.publishCreateReturns
	fake.recordInvocation("PublishCreate", []interface{}{arg1, arg2})
	fake.publishCreateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *TaskPublisher) PublishCreateCallCount() int {
	fake.publishCreateMutex.RLock()
	defer fake.publishCreateMutex.RUnlock()
	return len(fake.publishCreateArgsForCall)
}

func (fake *TaskPublisher) PublishCreateCalls(stub func(context.Context, pkg.Candidate) bool) {
	fake.publishCreateMutex.Lock()
	defer fake.publishCreateMutex.Unlock()
	fake.PublishCreateStub = stub
}

func (fake *TaskPublisher) PublishCreateArgsForCall(i int) (context.Context, pkg.Candidate) {
	fake.publishCreateMutex.RLock()
	defer fake.publishCreateMutex.RUnlock()
	argsForCall := fake.publishCreateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *TaskPublisher) PublishCreateReturns(result1 bool) {
	fake.publishCreateMutex.Lock()
	defer fake.publishCreateMutex.Unlock()
	fake.PublishCreateStub = nil
	fake.publishCreateReturns = struct {
		result1 bool
	}{result1}
}

func (fake *TaskPublisher) PublishCreateReturnsOnCall(i int, result1 bool) {
	fake.publishCreateMutex.Lock()
	defer fake.publishCreateMutex.Unlock()
	fake.PublishCreateStub = nil
	if fake.publishCreateReturnsOnCall == nil {
		fake.publishCreateReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.publishCreateReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *TaskPublisher) PublishDecision(arg1 context.Context, arg2 pkg.Candidate) bool {
	fake.publishDecisionMutex.Lock()
	ret, specificReturn := fake.publishDecisionReturnsOnCall[len(fake.publishDecisionArgsForCall)]
	fake.publishDecisionArgsForCall = append(fake.publishDecisionArgsForCall, struct {
		arg1 context.Context
		arg2 pkg.Candidate
	}{arg1, arg2})
	stub := fake.PublishDecisionStub
	fakeReturns := fake.publishDecisionReturns
	fake.recordInvocation("PublishDecision", []interface{}{arg1, arg2})
	fake.publishDecisionMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *TaskPublisher) PublishDecisionCallCount() int {
	fake.publishDecisionMutex.RLock()
	defer fake.publishDecisionMutex.RUnlock()
	return len(fake.publishDecisionArgsForCall)
}

func (fake *TaskPublisher) PublishDecisionCalls(stub func(context.Context, pkg.Candidate) bool) {
	fake.publishDecisionMutex.Lock()
	defer fake.publishDecisionMutex.Unlock()
	fake.PublishDecisionStub = stub
}

func (fake *TaskPublisher) PublishDecisionArgsForCall(i int) (context.Context, pkg.Candidate) {
	fake.publishDecisionMutex.RLock()
	defer fake.publishDecisionMutex.RUnlock()
	argsForCall := fake.publishDecisionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *TaskPublisher) PublishDecisionReturns(result1 bool) {
	fake.publishDecisionMutex.Lock()
	defer fake.publishDecisionMutex.Unlock()
	fake.PublishDecisionStub = nil
	fake.publishDecisionReturns = struct {
		result1 bool
	}{result1}
}

func (fake *TaskPublisher) PublishDecisionReturnsOnCall(i int, result1 bool) {
	fake.publishDecisionMutex.Lock()
	defer fake.publishDecisionMutex.Unlock()
	fake.PublishDecisionStub = nil
	if fake.publishDecisionReturnsOnCall == nil {
		fake.publishDecisionReturnsOnCall = make(map[int]struct {
			result1 bool
		})
	}
	fake.publishDecisionReturnsOnCall[i] = struct {
		result1 bool
	}{result1}
}

func (fake *TaskPublisher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *TaskPublisher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ pkg.TaskPublisher = new(TaskPublisher)
